<?php

namespace AppBundle\Repository;

/**
 * EstablishmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablishmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
